package edu.iastate.pathwayaccess.cytoscape.ClientUI;

//import cytoscape.util.OpenBrowser;
import javax.swing.JOptionPane;
import javax.swing.event.HyperlinkEvent;

/**
 *
 * @author Greg
 */
public class pnlDetails extends javax.swing.JPanel {

    /**
     * Stores the containing frame
     */
    javax.swing.JFrame frame;

    /** Creates new form pnlDetails */
    public pnlDetails(javax.swing.JFrame frame) {
        this.frame = frame;
        initComponents();
    }

    /**
     * Sets the text pane's text to the given string
     * @param html String to set the text to
     */
    public void setText(String html)
    {
        txtResultDetails.setText(html);
        txtResultDetails.setCaretPosition(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                scrResultDetails = new javax.swing.JScrollPane();
                txtResultDetails = new javax.swing.JTextPane();
                lblDetails = new javax.swing.JLabel();

                setMinimumSize(new java.awt.Dimension(100, 100));

                txtResultDetails.setContentType("text/html");
                txtResultDetails.setEditable(false);
                txtResultDetails.setText("<html>\r\n  <head>\r\n\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      \n    </p>\r\n  </body>\r\n</html>\r\n");
                txtResultDetails.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                txtResultDetailsMouseClicked(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                txtResultDetailsMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                txtResultDetailsMouseExited(evt);
                        }
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                txtResultDetailsMousePressed(evt);
                        }
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                txtResultDetailsMouseReleased(evt);
                        }
                });
                txtResultDetails.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
                        public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                                txtResultDetailsHyperlinkUpdate(evt);
                        }
                });
                scrResultDetails.setViewportView(txtResultDetails);

                lblDetails.setText("<html><b>Details:</b></html>");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDetails)
                                .addContainerGap(124, Short.MAX_VALUE))
                        .addComponent(scrResultDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrResultDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

    private void txtResultDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResultDetailsMouseClicked
        //Do nothing: Stops any mouse events from occuring inside the text pane
}//GEN-LAST:event_txtResultDetailsMouseClicked

    private void txtResultDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResultDetailsMouseEntered
        //Do nothing: Stops any mouse events from occuring inside the text pane
}//GEN-LAST:event_txtResultDetailsMouseEntered

    private void txtResultDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResultDetailsMouseExited
        //Do nothing: Stops any mouse events from occuring inside the text pane
}//GEN-LAST:event_txtResultDetailsMouseExited

    private void txtResultDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResultDetailsMousePressed
        //Do nothing: Stops any mouse events from occuring inside the text pane
}//GEN-LAST:event_txtResultDetailsMousePressed

    private void txtResultDetailsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResultDetailsMouseReleased
        //Do nothing: Stops any mouse events from occuring inside the text pane
}//GEN-LAST:event_txtResultDetailsMouseReleased

    /**
     * Opens the URL of a hyperlink activated event
     * @param evt Hyperlink activated event
     */
    private void txtResultDetailsHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_txtResultDetailsHyperlinkUpdate
        if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            
                try {
                    //OpenBrowser.openURL(evt.getURL().toString());
                    java.awt.Desktop.getDesktop().browse(evt.getURL().toURI());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(frame,
                        "Unable to open the link.",
                        "Browser Error",
                        JOptionPane.ERROR_MESSAGE);
                }
        }
    }//GEN-LAST:event_txtResultDetailsHyperlinkUpdate


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel lblDetails;
        private javax.swing.JScrollPane scrResultDetails;
        private javax.swing.JTextPane txtResultDetails;
        // End of variables declaration//GEN-END:variables

}
