package edu.iastate.pathwayaccess.cytoscape.ClientUI;

import edu.iastate.pathwayaccess.cytoscape.PropertiesInterface;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.HyperlinkEvent;

/**
 * Creates a panel with just an un-editable text field
 * @author Greg
 */
public class pnlNoSearchResults extends javax.swing.JPanel {
    /**
     * Stores the containing frame
     */
    private JFrame frame;

    /**
     * Creates new form pnlPreSearch with the default MetNet Web Service
     * Client description.
     */
    public pnlNoSearchResults(JFrame frame, PropertiesInterface properties) {
        this(frame, properties, null);
    }

    /**
     * Creates new form pnlPreSearch with the given text or, if null, the
     * default MetNet Web Service Client description.
     * @param text Text to set the text field to or null for the default
     * MetNet Web Service Client description.
     */
    public pnlNoSearchResults(JFrame frame, PropertiesInterface properties, String text)
    {
        this.frame = frame;
        if(properties == null)
            throw new NullPointerException("Properties cannot be null");
        initComponents();

        //Set the default text
        if(text == null)
            txtDetails.setText(properties.databaseDescription());
        else
            txtDetails.setText(text);
        txtDetails.setCaretPosition(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                scrDetails = new javax.swing.JScrollPane();
                txtDetails = new javax.swing.JTextPane();

                setPreferredSize(new java.awt.Dimension(490, 316));

                txtDetails.setContentType("text/html");
                txtDetails.setEditable(false);
                txtDetails.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
                        public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                                txtDetailsHyperlinkUpdate(evt);
                        }
                });
                scrDetails.setViewportView(txtDetails);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scrDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scrDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                );
        }// </editor-fold>//GEN-END:initComponents

    /**
     * Opens the URL of a hyperlink activated event
     * @param evt Hyperlink activated event
     */
    private void txtDetailsHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_txtDetailsHyperlinkUpdate
        if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {

                try {
                    //OpenBrowser.openURL(evt.getURL().toString());
                    java.awt.Desktop.getDesktop().browse(evt.getURL().toURI());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(frame,
                        "Unable to open the link.",
                        "Browser Error",
                        JOptionPane.ERROR_MESSAGE);
                }
        }
    }//GEN-LAST:event_txtDetailsHyperlinkUpdate


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane scrDetails;
        private javax.swing.JTextPane txtDetails;
        // End of variables declaration//GEN-END:variables

}
